-- Generated by infa2dbt
{% macro generate_md5_hash(fields) %}
  MD5(
    {% for field in fields %}
      {{ field }}
      {%- if not loop.last %} || '|' || {% endif %}
    {% endfor %}
  )
{% endmacro %}
