-- Generated by infa2dbt
{% macro generate_md5_hash(field_list) %}
    MD5(
        {% for field in field_list %}
            COALESCE({{ field }}, '') || '|'
            {%- if not loop.last %} || {% endif -%}
        {% endfor %}
    )
{% endmacro %}
