-- Generated by infa2dbt
{{ config(materialized='view') }}

WITH source_data AS (
    SELECT
        pf.PTNR_CUST_NBR,
        cm.CENTRAL_ORDR_BLK,
        cm.CUST_NBR,
        cm.ATTRIBUTE_9,
        ca.NAME_1,
        ca.CITY,
        ca.REGION_KEY,
        ca.PO_CD,
        ca.STRT_1,
        ca.STRT_2,
        ca.STRT_3
    FROM {{ source('mock_sources', 'ptnr_fctn') }} pf
    LEFT JOIN {{ source('mock_sources', 'cust_master') }} cm
        ON pf.PTNR_CUST_NBR = cm.CUST_NBR
    LEFT JOIN {{ source('mock_sources', 'cust_adrs') }} ca
        ON cm.CUST_NBR = ca.CUST_NBR
),

lkp_bus_ptnr_ids AS (
    SELECT
        BUS_PTNR_NBR,
        BUS_ID_NBR
    FROM {{ source('mock_sources', 'bus_ptnr_ids') }}
),

transformed_data AS (
    SELECT
        s.*,
        -- exp_EXPTRANS transformation
        IFF(
            s.CENTRAL_ORDR_BLK = '01' OR s.CENTRAL_ORDR_BLK = 'ZB',
            'I',
            IFF(s.CENTRAL_ORDR_BLK IS NULL, 'A', NULL)
        ) AS o_central_ordr_blk,
        l.BUS_ID_NBR
    FROM source_data s
    LEFT JOIN lkp_bus_ptnr_ids l
        ON s.CUST_NBR = l.BUS_PTNR_NBR
)

SELECT
    -- exp_DATA transformations
    '01' AS ACCT_RECVBL_OFFC_CDE,
    PTNR_CUST_NBR AS CUST_NBR,
    COALESCE(NAME_1, ' ') AS CUST_NME,
    COALESCE(PTNR_CUST_NBR, ' ') AS BILLING_CUST_NBR,
    COALESCE(CITY, ' ') AS CUST_CITY_NME,
    COALESCE(REGION_KEY, ' ') AS STATE_ALPHA_CDE,
    COALESCE(PO_CD, ' ') AS ZIP_CDE,
    STRT_1 AS ADDRESS_LINE1_DES,
    STRT_2 AS ADDRESS_LINE2_DES,
    STRT_3 AS ADDRESS_LINE3_DES,
    COALESCE(BUS_ID_NBR, 'NA') AS SMG_ID,
    CASE
        WHEN o_central_ordr_blk = 'I' THEN '1'
        WHEN o_central_ordr_blk = 'A' THEN '2'
        WHEN o_central_ordr_blk IS NULL THEN '3'
        ELSE NULL
    END AS CUST_ALT_SHIP_VIA_CDE,
    ATTRIBUTE_9 AS CUST_CLASS_CDE,
    NULL AS SALES_AREA_ID,
    NULL AS SALES_TERRITORY_ID,
    NULL AS SALES_ASSOCIATE_ID,
    NULL AS CUST_ALIAS_NME,
    NULL AS CUST_DEF_PROFILE
FROM transformed_data
