-- Generated by infa2dbt
{{ config(
    materialized='incremental',
    unique_key='DIM_EQUIPMENT_ID',
    merge_update_columns=['EDW_UPDATE_USER', 'EDW_UPDATE_TMS', 'EDW_END_EFCTV_DT', 'EDW_CURRENT_FLG']
) }}

SELECT
    DIM_EQUIPMENT_ID,
    EDW_UPDATE_USER,
    EDW_UPDATE_TMS,
    EDW_END_EFCTV_DT,
    EDW_CURRENT_FLG
FROM {{ ref('int_dim_equipment_soft_delete') }}

{% if is_incremental() %}
WHERE EDW_UPDATE_TMS > (SELECT COALESCE(MAX(EDW_UPDATE_TMS), '1900-01-01') FROM {{ this }})
{% endif %}
