-- Generated by infa2dbt
{{ config(materialized='table') }}

WITH equipment_data AS (
    SELECT * FROM {{ ref('int_equipment_lookups') }}
),

transformed_data AS (
    SELECT
        -- Generate new ID or use existing
        COALESCE(TRY_TO_NUMBER(EXISTING_DIM_EQUIPMENT_ID), TRY_TO_NUMBER(MAX_DIM_EQUIPMENT_ID) + ROW_NUMBER() OVER (ORDER BY EQPMNT_ID)) AS DIM_EQUIPMENT_ID,

        -- MD5 Hash for Business Process Key (50 fields)
        {{ generate_md5_hash([
            'COALESCE(EQPUN_NBR, \'\')', 'COALESCE(MARK_CD, \'\')', 'COALESCE(AAR_CAR_CD, \'\')',
            'COALESCE(TO_VARCHAR(AAR_CAR_CODE_ID), \'\')', 'COALESCE(EQPMNT_GROUP_CD, \'\')',
            'COALESCE(TO_VARCHAR(AXLE_QTY), \'\')', 'COALESCE(TO_VARCHAR(BUILT_DT), \'\')',
            'COALESCE(DMTR_UOM_BASIS_CD, \'\')', 'COALESCE(EIN_NBR, \'\')',
            'COALESCE(TO_VARCHAR(GROSS_WEIGHT_QTY), \'\')', 'COALESCE(GROSS_WEIGHT_UOM_BASIS_CD, \'\')',
            'COALESCE(LINEAL_FRCTNL_UOM_BASIS_CD, \'\')', 'COALESCE(LINEAL_UOM_BASIS_CD, \'\')',
            'COALESCE(LIQUID_UOM_BASIS_CD, \'\')', 'COALESCE(TO_VARCHAR(OTSD_EXTRM_HEIGHT_QTY), \'\')',
            'COALESCE(TO_VARCHAR(OTSD_EXTRM_WIDTH_QTY), \'\')', 'COALESCE(TO_VARCHAR(OTSD_HEIGHT_EXTRM_WIDTH_QTY), \'\')',
            'COALESCE(TO_VARCHAR(OTSD_LENGTH_QTY), \'\')', 'COALESCE(OWNER_MARK_CD, \'\')',
            'COALESCE(LESSEE_MARK_CD, \'\')', 'COALESCE(PRIOR_EQPUN_NBR, \'\')',
            'COALESCE(PRIOR_MARK_CD, \'\')', 'COALESCE(SPEED_UOM_BASIS_CD, \'\')',
            'COALESCE(STATUS_CD, \'\')', 'COALESCE(SRVC_LIFE_CD, \'\')',
            'COALESCE(STNCL_MARK_OWNER_CLASS_CD, \'\')', 'COALESCE(TO_VARCHAR(TARE_WEIGHT_QTY), \'\')',
            'COALESCE(VOLUME_UOM_BASIS_CD, \'\')', 'COALESCE(WEIGHT_UOM_BASIS_CD, \'\')',
            'COALESCE(MCHNCL_DSGNTN_CD, \'\')', 'COALESCE(PLATE_CLRNC_CD, \'\')',
            'COALESCE(RBLT_CD, \'\')', 'COALESCE(TO_VARCHAR(RBLT_DT), \'\')',
            'COALESCE(RATE_CD, \'\')', 'COALESCE(TO_VARCHAR(EQPMNT_POOL_ID), \'\')',
            'COALESCE(TO_VARCHAR(EFCTV_TMS), \'\')', 'COALESCE(REGISTERED_IND, \'\')',
            'COALESCE(MARK_OWNER_CTGRY_CD, \'\')', 'COALESCE(CAR_KIND_CD, \'\')',
            'COALESCE(CPR_EQPMNT_POOL_ID, \'\')', 'COALESCE(AAR_EQPMNT_POOL_ID, \'\')',
            'COALESCE(TO_VARCHAR(HRSPWR_QTY), \'\')', '\'\'', '\'\'', '\'\'', '\'\'', '\'\'', '\'\'', '\'\'', '\'\''
        ]) }} AS EDW_SRC_BPK_MD5_ID,

        -- MD5 Hash for Business Key
        {{ generate_md5_hash(['COALESCE(EQPUN_NBR, \'\')', 'COALESCE(MARK_CD, \'\')']) }} AS EDW_SRC_BK_MD5_ID,

        -- EDW Metadata
        '{{ var("etl_user", "DBT_USER") }}' AS EDW_CREATE_USER,
        CURRENT_TIMESTAMP() AS EDW_CREATE_TMS,
        '{{ var("etl_user", "DBT_USER") }}' AS EDW_UPDATE_USER,
        CURRENT_TIMESTAMP() AS EDW_UPDATE_TMS,
        CURRENT_TIMESTAMP() AS EDW_START_EFCTV_DT,
        NULL AS EDW_END_EFCTV_DT,
        'Y' AS EDW_CURRENT_FLG,

        -- Equipment attributes
        EQPUN_NBR,
        MARK_CD,
        AAR_CAR_CD,
        AAR_CAR_CODE_ID AS AAR_CAR_CD_ID,
        EQPMNT_GROUP_CD,
        AXLE_QTY,
        BUILT_DT,
        DMTR_UOM_BASIS_CD,
        EIN_NBR,
        GROSS_WEIGHT_QTY,
        GROSS_WEIGHT_UOM_BASIS_CD,
        LINEAL_FRCTNL_UOM_BASIS_CD,
        LINEAL_UOM_BASIS_CD,
        LIQUID_UOM_BASIS_CD,
        OTSD_EXTRM_HEIGHT_QTY,
        OTSD_EXTRM_WIDTH_QTY,
        OTSD_HEIGHT_EXTRM_WIDTH_QTY,
        OTSD_LENGTH_QTY,
        OWNER_MARK_CD,
        LESSEE_MARK_CD,
        PRIOR_EQPUN_NBR,
        PRIOR_MARK_CD,
        SPEED_UOM_BASIS_CD,
        STATUS_CD,
        SRVC_LIFE_CD,
        STNCL_MARK_OWNER_CLASS_CD,
        TARE_WEIGHT_QTY,
        VOLUME_UOM_BASIS_CD,
        WEIGHT_UOM_BASIS_CD,
        MCHNCL_DSGNTN_CD,
        PLATE_CLRNC_CD,
        RBLT_CD,
        RBLT_DT,
        RATE_CD,

        -- Derived attributes
        CASE
            WHEN MARK_OWNER_CTGRY_CD = 'P' THEN 'Private'
            WHEN MARK_OWNER_CTGRY_CD = 'R' THEN 'Railroad'
            ELSE 'Unknown'
        END AS CAR_OWNERSHIP,

        CASE
            WHEN LESSEE_MARK_CD IS NOT NULL THEN 'Leased'
            ELSE 'Not Leased'
        END AS LEASED_IND,

        NULL AS TARGET_EQPMT_CTGRY_NM,
        NULL AS PRDCT_NM,
        NULL AS FLEET_NM,
        EQPMNT_POOL_ID,
        NULL AS FLEET_SBGRP_CTGRY_NM,
        NULL AS PARTY_NM,
        CAR_KIND_CD,
        NULL AS UCA_CODES,
        CPR_EQPMNT_POOL_ID,
        AAR_EQPMNT_POOL_ID,
        EFCTV_TMS,
        EFCTV_TMS AS MAX_EFCTV_TMS,
        REGISTERED_IND,
        CASE WHEN MARK_CD LIKE 'CP%' THEN 'Y' ELSE 'N' END AS CP_OWNED_IND,
        DLTD_TMS

    FROM equipment_data
)

SELECT * FROM transformed_data
