-- Generated by infa2dbt
{{ config(materialized='table') }}

WITH validated AS (
    SELECT * FROM {{ ref('int_citibank_vca_validated') }}
    WHERE VALIDATION_STATUS = 'VALID'
),

enriched AS (
    SELECT
        -- Primary identifiers
        RECORD_ID,
        ACTION_TYPE,
        ISSUER_ID,
        ICA_NBR,
        BANK_NBR,

        -- User and request
        USER_NAME,
        REQUEST_ID,

        -- Financial attributes
        MIN_PURCHASE_AMT,
        MAX_PURCHASE_AMT,
        PURCHASE_CURRENCY,
        PURCHASE_TYPE,

        -- Amount categorization
        CASE
            WHEN MAX_PURCHASE_AMT >= 10000 THEN 'HIGH_VALUE'
            WHEN MAX_PURCHASE_AMT >= 1000 THEN 'MEDIUM_VALUE'
            ELSE 'LOW_VALUE'
        END AS AMOUNT_CATEGORY,

        -- Virtual card
        V_CARD_ALIAS,
        MULTI_USE,

        -- Supplier info
        SUPPLIER_NAME,
        SUPPLIER_EMAIL,

        -- Validity period
        VALID_FROM,
        VALID_TO,
        VALID_FOR,

        -- CDF payment details
        CDF_PAYMENT_NUMBER,
        CDF_PAYEE_NUMBER,
        CDF_PAYMENT_AMOUNT,
        CDF_PAYMENT_DATE,
        CDF_PAYEE_NAME,

        -- Action type description
        CASE
            WHEN ACTION_TYPE = 'A' THEN 'ADD'
            WHEN ACTION_TYPE = 'U' THEN 'UPDATE'
            WHEN ACTION_TYPE = 'D' THEN 'DELETE'
            ELSE 'UNKNOWN'
        END AS ACTION_DESCRIPTION,

        -- Generated file reference
        FILE_NAME,

        -- Audit
        CURRENT_TIMESTAMP() AS ETL_LOAD_TIMESTAMP

    FROM validated
)

SELECT * FROM enriched
