"""Regression tests for all bug fixes (C1-C5, H1, H5, H6, M1, M2).

Each test class targets one specific bug fix to prevent regressions.
"""

from __future__ import annotations

import json
import re
import textwrap
from pathlib import Path
from typing import List, Set
from unittest.mock import MagicMock, patch

import pytest
import yaml

from informatica_to_dbt.generator.post_processor import (
    _convert_isnull_boolean,
    _convert_nvl2,
    _fix_informatica_residuals,
    post_process,
)
from informatica_to_dbt.generator.response_parser import GeneratedFile
from informatica_to_dbt.validator.patterns import INFORMATICA_FN_RE, INFORMATICA_PATTERN_RE
from informatica_to_dbt.xml_parser.models import (
    Connector,
    Instance,
    Mapping,
    Transformation,
    TransformField,
)


# ---------------------------------------------------------------------------
# C1 — dbt_project.yml read-merge-write (no overwrite)
# ---------------------------------------------------------------------------


class TestC1ProjectYmlMerge:
    """C1: _write_project_yml must preserve prior mapping configs."""

    def test_existing_mappings_preserved(self, tmp_path):
        """When dbt_project.yml already has mapping A and we write mapping B,
        both A and B must appear in the final file."""
        from informatica_to_dbt.merger.project_merger import ProjectMerger, MergeResult
        from informatica_to_dbt.orchestrator import MappingResult
        from informatica_to_dbt.config import Config

        project_dir = tmp_path / "dbt_project"
        project_dir.mkdir()

        # Pre-populate an existing dbt_project.yml with mapping_a
        existing_yml = textwrap.dedent("""\
            # -- Generated by infa2dbt
            name: 'test_project'
            version: '1.0.0'
            profile: 'informatica_to_dbt_migration'
            require-dbt-version: ['>=1.7.0', '<2.0.0']
            model-paths: ['models']
            analysis-paths: ['analyses']
            test-paths: ['tests']
            seed-paths: ['seeds']
            macro-paths: ['macros']
            snapshot-paths: ['snapshots']
            clean-targets:
              - 'target'
              - 'dbt_packages'
            models:
              test_project:
                mapping_a:
                  +tags: ['mapping_a']
                  staging:
                    +materialized: view
        """)
        (project_dir / "dbt_project.yml").write_text(existing_yml, encoding="utf-8")

        # Create a MappingResult for mapping_b with a staging file
        mr_b = MappingResult(
            mapping_name="mapping_b",
            workflow_name="wf_test",
            files=[
                GeneratedFile("models/mapping_b/staging/stg_b.sql", "SELECT 1"),
            ],
        )

        config = Config()
        config.project_dir = str(project_dir)
        config.dbt_project_name = "test_project"
        config.merge_mode = "merge"

        merger = ProjectMerger(config)
        result = merger.merge([mr_b])

        # Re-read the dbt_project.yml
        final = yaml.safe_load(
            (project_dir / "dbt_project.yml").read_text(encoding="utf-8")
        )
        project_models = final["models"]["test_project"]

        # Both mapping_a (existing) and mapping_b (new) must be present
        assert "mapping_a" in project_models, "Existing mapping_a was overwritten"
        assert "mapping_b" in project_models, "New mapping_b not written"


# ---------------------------------------------------------------------------
# C2 — EWI report read-merge-write (no overwrite)
# ---------------------------------------------------------------------------


class TestC2EwiReportMerge:
    """C2: EWI write_json must merge, not overwrite, prior mapping entries."""

    def test_existing_mapping_preserved_in_json(self, tmp_path):
        """When JSON report already has mapping A, writing mapping B must
        keep both in the output."""
        from informatica_to_dbt.reports.ewi_report import EWIReport, EWIReportGenerator, EWIItem
        from informatica_to_dbt.metrics import RepositoryMetrics, MappingMetrics

        # Build an existing report with one mapping
        existing_report = {
            "title": "Test",
            "generated_at": "2024-01-01 00:00:00",
            "summary": {
                "mappings": [
                    {
                        "mapping_name": "m_old",
                        "status": "success",
                        "total_seconds": 1.0,
                        "llm_calls": 1,
                        "llm_total_seconds": 0.5,
                        "complexity_score": 30,
                        "strategy": "DIRECT",
                        "quality_score": 90.0,
                        "total_errors": 0,
                        "total_warnings": 0,
                        "files_generated": 3,
                        "self_heal_rounds": 0,
                        "cache_hit": False,
                    }
                ],
                "total_seconds": 1.0,
                "total_mappings": 1,
                "successful": 1,
                "failed": 0,
                "success_rate": 100.0,
            },
            "items": [
                {
                    "level": "info",
                    "mapping_name": "m_old",
                    "code": "I001",
                    "message": "Conversion succeeded",
                    "detail": "",
                }
            ],
        }

        json_path = tmp_path / "ewi_report.json"
        json_path.write_text(json.dumps(existing_report), encoding="utf-8")

        # Now write a new report for mapping m_new
        m_metrics = MappingMetrics(mapping_name="m_new")
        m_metrics.status = "success"
        m_metrics.total_seconds = 2.0
        repo_metrics = RepositoryMetrics(
            mapping_metrics=[m_metrics], total_seconds=2.0,
        )

        new_report = EWIReport(
            repository_metrics=repo_metrics,
            items=[
                EWIItem(
                    level="info",
                    mapping_name="m_new",
                    code="I001",
                    message="Conversion succeeded",
                ),
            ],
        )

        generator = EWIReportGenerator()
        generator.write_json(new_report, str(json_path))

        result = json.loads(json_path.read_text(encoding="utf-8"))
        mapping_names = [
            m["mapping_name"]
            for m in result["summary"]["mappings"]
        ]
        assert "m_old" in mapping_names, "Existing m_old was lost"
        assert "m_new" in mapping_names, "New m_new not written"

        # Items from both should be present
        item_mappings = [i["mapping_name"] for i in result["items"]]
        assert "m_old" in item_mappings
        assert "m_new" in item_mappings


# ---------------------------------------------------------------------------
# C3 — nested ISNULL balanced-paren conversion
# ---------------------------------------------------------------------------


class TestC3NestedIsnull:
    """C3: _convert_isnull_boolean must handle nested parens correctly."""

    def test_simple_isnull(self):
        result = _convert_isnull_boolean("ISNULL(X)")
        assert result == "(X IS NULL)"

    def test_nested_isnull_trim(self):
        """ISNULL(TRIM(X)) must not break the paren matching."""
        result = _convert_isnull_boolean("ISNULL(TRIM(X))")
        assert result == "(TRIM(X) IS NULL)"

    def test_deeply_nested_isnull(self):
        """ISNULL(UPPER(TRIM(X))) must balance correctly."""
        result = _convert_isnull_boolean("ISNULL(UPPER(TRIM(X)))")
        assert result == "(UPPER(TRIM(X)) IS NULL)"

    def test_two_arg_isnull_left_alone(self):
        """Two-arg form ISNULL(x, default) should NOT be converted to IS NULL."""
        result = _convert_isnull_boolean("ISNULL(X, 0)")
        # Two-arg form stays as-is for the later ISNULL→IFNULL mapping
        assert "IS NULL" not in result
        assert "ISNULL" in result

    def test_case_insensitive(self):
        result = _convert_isnull_boolean("isnull(col_a)")
        assert result == "(col_a IS NULL)"


# ---------------------------------------------------------------------------
# C4 — nested NVL2 balanced-paren conversion
# ---------------------------------------------------------------------------


class TestC4NestedNvl2:
    """C4: _convert_nvl2 must handle nested parens correctly."""

    def test_simple_nvl2(self):
        result = _convert_nvl2("NVL2(X, 'yes', 'no')")
        assert result == "IFF(X IS NOT NULL, 'yes', 'no')"

    def test_nested_nvl2_trim(self):
        """NVL2(TRIM(X), a, b) must balance nested parens."""
        result = _convert_nvl2("NVL2(TRIM(X), 'a', 'b')")
        assert result == "IFF(TRIM(X) IS NOT NULL, 'a', 'b')"

    def test_nested_nvl2_in_args(self):
        """NVL2 with nested function calls in all arguments."""
        result = _convert_nvl2("NVL2(TRIM(X), UPPER(Y), LOWER(Z))")
        assert result == "IFF(TRIM(X) IS NOT NULL, UPPER(Y), LOWER(Z))"

    def test_case_insensitive(self):
        result = _convert_nvl2("nvl2(a, b, c)")
        assert result == "IFF(a IS NOT NULL, b, c)"


# ---------------------------------------------------------------------------
# C5 — false positive residual pattern detection
# ---------------------------------------------------------------------------


class TestC5ResidualPatterns:
    """C5: NVL and simple DECODE must NOT trigger false positives in
    INFORMATICA_FN_RE after proper conversion."""

    def test_coalesce_not_flagged(self):
        """NVL converted to COALESCE should not be flagged as a residual."""
        assert INFORMATICA_FN_RE.search("COALESCE(x, 0)") is None, \
            "COALESCE should not be flagged as an Informatica residual"

    def test_case_when_not_flagged(self):
        """DECODE converted to CASE WHEN should not be flagged."""
        converted = "CASE WHEN status = 'A' THEN 1 ELSE 0 END"
        assert INFORMATICA_FN_RE.search(converted) is None, \
            "CASE WHEN should not be flagged as an Informatica residual"

    def test_nvl2_still_detected(self):
        """Unconverted NVL2 should still be detected as a residual."""
        assert INFORMATICA_FN_RE.search("NVL2(x, y, z)") is not None, \
            "NVL2 must still be detected as a residual"

    def test_iif_still_detected(self):
        """IIF (unconverted) should still be detected."""
        assert INFORMATICA_FN_RE.search("IIF(x, 1, 0)") is not None, \
            "IIF must still be detected as a residual"

    def test_pattern_list_not_empty(self):
        """INFORMATICA_FN_RE must have content."""
        assert INFORMATICA_FN_RE.pattern, "Pattern must not be empty"


# ---------------------------------------------------------------------------
# H1 — XXE vulnerability (DOCTYPE stripping)
# ---------------------------------------------------------------------------


class TestH1XxeSafety:
    """H1: XML parser must strip DOCTYPE declarations before parsing."""

    def test_doctype_stripped_before_parse(self):
        """XML with DOCTYPE containing ENTITY must parse without executing."""
        from informatica_to_dbt.xml_parser.parser import InformaticaXMLParser

        xxe_xml = textwrap.dedent("""\
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE foo [
              <!ENTITY xxe SYSTEM "file:///etc/passwd">
            ]>
            <POWERMART CREATION_DATE="01/01/2024">
              <REPOSITORY NAME="TEST" DATABASETYPE="Oracle" CODEPAGE="UTF-8">
                <FOLDER NAME="F1" SHARED="NOTSHARED">
                  <MAPPING NAME="m_test" ISVALID="YES">
                  </MAPPING>
                </FOLDER>
              </REPOSITORY>
            </POWERMART>
        """)

        parser = InformaticaXMLParser()
        # Should NOT raise and should NOT expand the entity
        repo = parser.parse(xxe_xml)
        assert repo.name == "TEST"

    def test_normal_xml_still_parses(self):
        """XML without DOCTYPE must still parse normally."""
        from informatica_to_dbt.xml_parser.parser import InformaticaXMLParser

        normal_xml = textwrap.dedent("""\
            <?xml version="1.0" encoding="UTF-8"?>
            <POWERMART CREATION_DATE="01/01/2024">
              <REPOSITORY NAME="NORMAL" DATABASETYPE="Oracle" CODEPAGE="UTF-8">
                <FOLDER NAME="F1" SHARED="NOTSHARED">
                  <MAPPING NAME="m_normal" ISVALID="YES">
                  </MAPPING>
                </FOLDER>
              </REPOSITORY>
            </POWERMART>
        """)

        parser = InformaticaXMLParser()
        repo = parser.parse(normal_xml)
        assert repo.name == "NORMAL"


# ---------------------------------------------------------------------------
# H5 — Sub-chain connector loss
# ---------------------------------------------------------------------------


class TestH5SubChainConnectors:
    """H5: When a chain is split into sub-groups, connectors between
    sub-groups must be preserved via connector_scope."""

    def test_collect_chain_objects_with_scope(self):
        """Connectors between sub-groups should be included when
        connector_scope covers the full parent chain."""
        from informatica_to_dbt.chunker.context_preserving import _collect_chain_objects

        mapping = Mapping(
            name="m_scope_test",
            transformations=[
                Transformation(name="SQ_A", type="Source Qualifier", fields=[]),
                Transformation(name="EXP_B", type="Expression", fields=[]),
                Transformation(name="TGT_C", type="Target Definition", fields=[]),
            ],
            instances=[
                Instance(name="SQ_A", transformation_name="SQ_A",
                         transformation_type="Source Qualifier"),
                Instance(name="EXP_B", transformation_name="EXP_B",
                         transformation_type="Expression"),
                Instance(name="TGT_C", transformation_name="TGT_C",
                         transformation_type="Target Definition", instance_type="TARGET"),
            ],
            connectors=[
                # SQ_A → EXP_B
                Connector(from_field="F1", from_instance="SQ_A",
                          from_instance_type="Source Qualifier",
                          to_field="F1", to_instance="EXP_B",
                          to_instance_type="Expression"),
                # EXP_B → TGT_C
                Connector(from_field="F1", from_instance="EXP_B",
                          from_instance_type="Expression",
                          to_field="F1", to_instance="TGT_C",
                          to_instance_type="Target Definition"),
            ],
        )

        full_chain = ["SQ_A", "EXP_B", "TGT_C"]

        # Without connector_scope: only SQ_A chunk — no connectors because
        # EXP_B is not in the chunk
        transforms, instances, connectors = _collect_chain_objects(
            mapping, ["SQ_A"], connector_scope=None,
        )
        assert len(connectors) == 0, "Without scope, cross-chunk connectors must be excluded"

        # With connector_scope = full chain: SQ_A → EXP_B connector should
        # be included because both ends are in the full chain scope
        transforms, instances, connectors = _collect_chain_objects(
            mapping, ["SQ_A"], connector_scope=full_chain,
        )
        assert len(connectors) == 1, "With scope, SQ_A→EXP_B connector must be included"
        assert connectors[0].from_instance == "SQ_A"
        assert connectors[0].to_instance == "EXP_B"

    def test_collect_chain_objects_both_ends_must_be_in_scope(self):
        """Connectors where one end is outside the scope must be excluded."""
        from informatica_to_dbt.chunker.context_preserving import _collect_chain_objects

        mapping = Mapping(
            name="m_scope_edge",
            transformations=[
                Transformation(name="A", type="Expression", fields=[]),
                Transformation(name="B", type="Expression", fields=[]),
                Transformation(name="OUTSIDE", type="Expression", fields=[]),
            ],
            instances=[
                Instance(name="A", transformation_name="A", transformation_type="Expression"),
                Instance(name="B", transformation_name="B", transformation_type="Expression"),
                Instance(name="OUTSIDE", transformation_name="OUTSIDE",
                         transformation_type="Expression"),
            ],
            connectors=[
                Connector(from_field="F", from_instance="A", from_instance_type="Expression",
                          to_field="F", to_instance="B", to_instance_type="Expression"),
                # This connector has one end outside the scope
                Connector(from_field="F", from_instance="B", from_instance_type="Expression",
                          to_field="F", to_instance="OUTSIDE", to_instance_type="Expression"),
            ],
        )

        # Scope is only [A, B] — OUTSIDE is not in scope
        transforms, instances, connectors = _collect_chain_objects(
            mapping, ["A"], connector_scope=["A", "B"],
        )
        assert len(connectors) == 1
        assert connectors[0].to_instance == "B"


# ---------------------------------------------------------------------------
# H6 — Multi-chunk model escalation
# ---------------------------------------------------------------------------


class TestH6MultiChunkEscalation:
    """H6: Model escalation must iterate over ALL chunks, not just chunks[0]."""

    def test_escalation_loop_iterates_all_chunks(self):
        """Verify that the escalation code in convert_mapping iterates
        over all chunks, not just chunks[0].  This is a structural test
        that inspects the source code for the 'for chunk in chunks' pattern
        inside the escalation block."""
        import inspect
        from informatica_to_dbt.orchestrator import convert_mapping

        source = inspect.getsource(convert_mapping)

        # The H6 fix added "for chunk in chunks:" inside the escalation block.
        # Verify this loop exists rather than the old "chunks[0]" pattern.
        assert "for chunk in chunks:" in source, \
            "Escalation must iterate 'for chunk in chunks:', not use chunks[0]"

        # Also verify we merge escalated chunks
        assert "esc_all_chunk_files" in source or "esc_merged" in source, \
            "Escalation must merge results from all chunks"

    def test_escalation_does_not_use_only_first_chunk(self):
        """Verify the old bug pattern (chunks[0] in escalation code) is gone.
        Comments mentioning the old pattern are acceptable."""
        import inspect
        from informatica_to_dbt.orchestrator import convert_mapping

        source = inspect.getsource(convert_mapping)

        # Find the escalation section (after 'llm_fallback_model')
        escalation_idx = source.find("llm_fallback_model")
        if escalation_idx > 0:
            escalation_section = source[escalation_idx:]
            # Strip comments to only check actual code
            code_lines = [
                line for line in escalation_section.splitlines()
                if line.strip() and not line.strip().startswith("#")
            ]
            code_only = "\n".join(code_lines)
            assert "chunks[0]" not in code_only, \
                "Escalation code must not reference chunks[0] — should iterate all chunks"


# ---------------------------------------------------------------------------
# M1 — NVL/NVL2 ordering fragility
# ---------------------------------------------------------------------------


class TestM1NvlOrdering:
    """M1: NVL simple-text replacement must NOT match NVL2."""

    def test_nvl_replaced_to_coalesce(self):
        """NVL(x, 0) should become COALESCE(x, 0)."""
        result = _fix_informatica_residuals("NVL(x, 0)")
        assert "COALESCE(x, 0)" in result
        assert "NVL" not in result

    def test_nvl2_not_corrupted_by_nvl_replacement(self):
        """NVL2(x, y, z) must NOT be partially matched by the NVL pattern.
        The pre-pass converts NVL2 to IFF, so the simple-text NVL→COALESCE
        should never see NVL2."""
        # Simulate what happens if _convert_nvl2 runs first (normal pipeline)
        after_nvl2_pass = _convert_nvl2("NVL2(X, 'a', 'b')")
        result = _fix_informatica_residuals(after_nvl2_pass)
        assert "COALESCE" not in result, "NVL2 should not be converted to COALESCE"
        assert "IFF(X IS NOT NULL" in result

    def test_nvl_and_nvl2_in_same_sql(self):
        """SQL containing both NVL and NVL2 must convert each correctly."""
        sql = "SELECT NVL(a, 0), NVL2(b, 'yes', 'no') FROM t"
        result = _fix_informatica_residuals(sql)
        assert "COALESCE(a, 0)" in result
        assert "IFF(b IS NOT NULL, 'yes', 'no')" in result

    def test_nvl_case_insensitive(self):
        result = _fix_informatica_residuals("nvl(x, 0)")
        assert "COALESCE(x, 0)" in result

    def test_nvl_with_single_space(self):
        """NVL (x, 0) with a single space — the fast-path check uses the
        dict key 'NVL(' literally, so only 'NVL(' (no extra space) triggers
        the replacement.  This test documents the expected boundary."""
        result = _fix_informatica_residuals("NVL(x, 0)")
        assert "COALESCE" in result

    def test_nvl_negative_lookahead_blocks_alphanumeric(self):
        """Verify the (?!\\w) lookahead prevents matching NVL2, NVLX, etc."""
        # Build the same regex pattern used in _fix_informatica_residuals
        pattern = re.compile(r"\bNVL(?!\w)\s*\(", re.IGNORECASE)
        assert pattern.search("NVL(x, 0)") is not None, "Should match NVL("
        assert pattern.search("NVL2(x, y, z)") is None, "Must NOT match NVL2("
        assert pattern.search("NVLX(x)") is None, "Must NOT match NVLX("
        assert pattern.search("nvl (x, 0)") is not None, "Should match nvl ("


# ---------------------------------------------------------------------------
# M2 — SQL injection via string interpolation
# ---------------------------------------------------------------------------


class TestM2ParameterizedQuery:
    """M2: schema_discovery.from_snowflake must use parameterized queries."""

    def _import_schema_discovery(self):
        """Import schema_discovery, skipping if lxml is unavailable."""
        try:
            from informatica_to_dbt.discovery.schema_discovery import (
                SchemaDiscovery,
                _sanitize_identifier,
            )
            return SchemaDiscovery, _sanitize_identifier
        except ImportError:
            pytest.skip("lxml unavailable — discovery package cannot be imported")

    def test_query_uses_bind_parameter(self):
        """The SQL query built for INFORMATION_SCHEMA.COLUMNS must use '?'
        for the WHERE clause value, not f-string interpolation."""
        import inspect
        SchemaDiscovery, _ = self._import_schema_discovery()

        source = inspect.getsource(SchemaDiscovery.from_snowflake)

        # Must contain bind parameter marker
        assert "WHERE TABLE_SCHEMA = ?" in source or "WHERE TABLE_SCHEMA = ?" in source, \
            "Query must use bind parameter for TABLE_SCHEMA"

        # Must NOT contain f-string interpolation for WHERE clause
        assert "'{safe_schema}'" not in source, \
            "Query must not use f-string interpolation for WHERE value"

    def test_cursor_execute_called_with_params(self):
        """Verify that cursor.execute is called with a params tuple."""
        SchemaDiscovery, _ = self._import_schema_discovery()

        mock_session = MagicMock()
        mock_cursor = MagicMock()
        mock_session.connection.cursor.return_value = mock_cursor
        mock_cursor.fetchall.return_value = []
        mock_cursor.description = []

        SchemaDiscovery.from_snowflake(mock_session, "MY_DB", "MY_SCHEMA")

        # Verify cursor.execute was called with a tuple param
        mock_cursor.execute.assert_called_once()
        call_args = mock_cursor.execute.call_args
        sql_arg = call_args[0][0]
        params_arg = call_args[0][1]

        assert "?" in sql_arg, "SQL must contain bind placeholder"
        assert params_arg == ("MY_SCHEMA",), \
            f"Bind params must be ('MY_SCHEMA',), got {params_arg}"

    def test_sanitize_identifier_strips_injection(self):
        """_sanitize_identifier must strip SQL injection characters."""
        _, _sanitize_identifier = self._import_schema_discovery()

        # Normal identifier passes through
        assert _sanitize_identifier("MY_SCHEMA") == "MY_SCHEMA"
        assert _sanitize_identifier("DB$1") == "DB$1"

        # Injection attempts are stripped
        assert _sanitize_identifier("MY'; DROP TABLE--") == "MYDROPTABLE"

        # Empty result raises ValueError
        with pytest.raises(ValueError):
            _sanitize_identifier("!@#%^&*()")
